<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Marko</string>
    <key>scopeName</key>
    <string>text.marko</string>
    <key>uuid</key>
    <string>46c8c3f8-cabe-466a-a633-5deafdc51253</string>
    <key>fileTypes</key>
    <array>
      <string>marko</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>CSS style block, eg: style { color: green }</string>
        <key>name</key>
        <string>meta.embedded.css</string>
        <key>contentName</key>
        <string>source.css</string>
        <key>begin</key>
        <string>^\s*(style)(\b[^\s]*\.css)?\s+({)</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Less style block, eg: style.less { color: green }</string>
        <key>name</key>
        <string>meta.embedded.less</string>
        <key>contentName</key>
        <string>source.less</string>
        <key>begin</key>
        <string>^\s*(style)(\b[^\s]*\.less)\s+({)</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css.less</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>SCSS style block, eg: style.scss { color: green }</string>
        <key>name</key>
        <string>meta.embedded.scss</string>
        <key>contentName</key>
        <string>source.scss</string>
        <key>begin</key>
        <string>^\s*(style)(\b[^\s]*\.scss)\s+({)</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.css.scss</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>JS/TS style block</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>^\s*(style)(\b[^\s]*\.[tj]s)\s+({)</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.builtin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.marko.css</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko.css</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko.css</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>comment</key>
        <string>Top level blocks parsed as JavaScript</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>^\s*(?:((?:static|server|client)\b)|(?=(?:class|import|export)\b))</string>
        <key>end</key>
        <string>(?=\n|$)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.static.marko</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>include</key>
        <string>#content-concise-mode</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>attrs</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>Attribute with optional value</string>
            <key>name</key>
            <string>meta.marko-attribute</string>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>(?:(key|on[a-zA-Z0-9_$-]+|[a-zA-Z0-9_$]+Change|no-update(?:-body)?(?:-if)?)|([a-zA-Z0-9_$][a-zA-Z0-9_$-]*)|(#[a-zA-Z0-9_$][a-zA-Z0-9_$-]*))(:[a-zA-Z0-9_$][a-zA-Z0-9_$-]*)?</string>
            <key>end</key>
            <string>(?=.|$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.attribute-name.marko</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.marko</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.function.attribute-name.marko</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>support.function.attribute-name.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#html-args-or-method</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attr-value</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>A ...spread attribute</string>
            <key>name</key>
            <string>meta.marko-spread-attribute</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>begin</key>
            <string>(\.\.\.)</string>
            <key>end</key>
            <string>(?=[,;\]]|/&gt;|(?&lt;=[^=&gt;])&gt;|(?&lt;!^|[!~*%&amp;^|?:]|[!~*%&amp;^|?/&lt;&gt;+=-]=|[=&gt;]&gt;|[^.]\.|[^-]-|[^+]\+|[a-zA-Z0-9%).&lt;\]}]\s/|[^.$\w]await|[^.$\w]async|[^.$\w]class|[^.$\w]function|[^.$\w]keyof|[^.$\w]new|[^.$\w]readonly|[^.$\w]infer|[^.$\w]typeof|[^.$\w]void)\s+(?![\n{(+!~*%&amp;^|?:]|[&lt;&gt;/=-]=|[=&gt;]&gt;|\.[^.]|-[^-]|/[^&gt;]|(?:in|instanceof|satisfies|as|extends)\s+[^:=/,;&gt;]))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#javascript-expression</string>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.spread.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>Consume any whitespace after a comma</string>
            <key>begin</key>
            <string>\s*(,(?!,))</string>
            <key>end</key>
            <string>(?=\S)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.comma.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
      </dict>
      <key>attr-value</key>
      <dict>
        <key>comment</key>
        <string>Attribute value</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>\s*(:?=)\s*</string>
        <key>end</key>
        <string>(?=[,;\]]|/&gt;|(?&lt;=[^=&gt;])&gt;|(?&lt;!^|[!~*%&amp;^|?:]|[!~*%&amp;^|?/&lt;&gt;+=-]=|[=&gt;]&gt;|[^.]\.|[^-]-|[^+]\+|[a-zA-Z0-9%).&lt;\]}]\s/|[^.$\w]await|[^.$\w]async|[^.$\w]class|[^.$\w]function|[^.$\w]keyof|[^.$\w]new|[^.$\w]readonly|[^.$\w]infer|[^.$\w]typeof|[^.$\w]void)\s+(?![\n{(+!~*%&amp;^|?:]|[&lt;&gt;/=-]=|[=&gt;]&gt;|\.[^.]|-[^-]|/[^&gt;]|(?:in|instanceof|satisfies|as|extends)\s+[^:=/,;&gt;]))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-expression</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>concise-html-block</key>
      <dict>
        <key>comment</key>
        <string>--- HTML block within concise mode content. ---</string>
        <key>name</key>
        <string>meta.section.marko-html-block</string>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>end</key>
        <string>\1</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-html-mode</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-html-line</key>
      <dict>
        <key>comment</key>
        <string>-- HTML line within concise mode content. (content-html-mode w/o scriptlet)</string>
        <key>name</key>
        <string>meta.section.marko-html-line</string>
        <key>match</key>
        <string>\s*(--+)(?=\s+\S)(.*)($)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#cdata</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#doctype</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#declaration</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#javascript-comments-after-whitespace</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#html-comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#tag-html</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Match escape characters in text.</string>
                <key>name</key>
                <string>text.marko</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#placeholder</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Match anything else as text.</string>
                <key>name</key>
                <string>text.marko</string>
                <key>match</key>
                <string>.+?</string>
              </dict>
            </array>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-semi-eol</key>
      <dict>
        <key>comment</key>
        <string>Match spaces followed by a semi that represents the end of the line in concise mode.</string>
        <key>begin</key>
        <string>\s*(;)</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.terminator.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-attr-group</key>
      <dict>
        <key>comment</key>
        <string>Matches a group of non newline sensitive attributes in square brackets.</string>
        <key>begin</key>
        <string>\s*(\[)</string>
        <key>end</key>
        <string>]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#concise-attr-group</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\s+</string>
            <key>end</key>
            <string>(?=\S)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attrs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-open-tag-content</key>
      <dict>
        <key>comment</key>
        <string>Handles everything from the start of the tag name until the body content begins.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-before-attrs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#concise-semi-eol</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>Matches unenclosed concise mode attributes.</string>
            <key>begin</key>
            <string>(?!^)[, \t]</string>
            <key>end</key>
            <string>(?=--)|(?=\n)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#concise-semi-eol</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#concise-attr-group</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>[ \t]+</string>
                <key>end</key>
                <string>(?=\S|\n)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#attrs</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#invalid</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>concise-comment-block</key>
      <dict>
        <key>comment</key>
        <string>--- Embedded concise comment content block. ---</string>
        <key>name</key>
        <string>meta.section.marko-comment-block</string>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>end</key>
        <string>\1</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-comment</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-comment-line</key>
      <dict>
        <key>comment</key>
        <string>-- Embedded concise comment content line.</string>
        <key>name</key>
        <string>meta.section.marko-comment-line</string>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-comment</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-script-block</key>
      <dict>
        <key>comment</key>
        <string>--- Embedded concise script content block. ---</string>
        <key>name</key>
        <string>meta.section.marko-script-block</string>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>end</key>
        <string>\1</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-script</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-script-line</key>
      <dict>
        <key>comment</key>
        <string>-- Embedded concise script content line.</string>
        <key>name</key>
        <string>meta.section.marko-script-line</string>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-script</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-style-block</key>
      <dict>
        <key>comment</key>
        <string>--- Embedded concise style content block. ---</string>
        <key>name</key>
        <string>meta.section.marko-style-block</string>
        <key>contentName</key>
        <string>source.css</string>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>end</key>
        <string>\1</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-style-block-less</key>
      <dict>
        <key>comment</key>
        <string>--- Embedded concise style content block. ---</string>
        <key>name</key>
        <string>meta.section.marko-style-block</string>
        <key>contentName</key>
        <string>source.less</string>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>end</key>
        <string>\1</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-less</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-style-block-scss</key>
      <dict>
        <key>comment</key>
        <string>--- Embedded concise style content block. ---</string>
        <key>name</key>
        <string>meta.section.marko-style-block</string>
        <key>contentName</key>
        <string>source.scss</string>
        <key>begin</key>
        <string>\s*(--+)\s*$</string>
        <key>end</key>
        <string>\1</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-scss</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-style-line</key>
      <dict>
        <key>comment</key>
        <string>-- Embedded concise style content line.</string>
        <key>name</key>
        <string>meta.section.marko-style-line</string>
        <key>contentName</key>
        <string>source.css</string>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-style-line-less</key>
      <dict>
        <key>comment</key>
        <string>-- Embedded concise style content line.</string>
        <key>name</key>
        <string>meta.section.marko-style-line</string>
        <key>contentName</key>
        <string>source.less</string>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-less</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>concise-style-line-scss</key>
      <dict>
        <key>comment</key>
        <string>-- Embedded concise style content line.</string>
        <key>name</key>
        <string>meta.section.marko-style-line</string>
        <key>contentName</key>
        <string>source.scss</string>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>begin</key>
        <string>\s*(--+)</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#content-embedded-style-scss</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.embedded.scope.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>content-concise-mode</key>
      <dict>
        <key>comment</key>
        <string>Concise mode content block.</string>
        <key>name</key>
        <string>meta.marko-concise-content</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#scriptlet</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#cdata</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doctype</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#concise-html-block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#concise-html-line</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-html</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>A concise html tag.</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>comment</key>
                <string>Concise Marko html-comment tag</string>
                <key>begin</key>
                <string>^(\s*)(?=html-comment\b)</string>
                <key>while</key>
                <string>(?=^(?:\s*[})\]`]|\*/|\s*$|\1\s+(\S|$)))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-comment-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-comment-line</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>comment</key>
                <string>Concise style tag less</string>
                <key>begin</key>
                <string>^(\s*)(?=(?:html-)?style\b[^\s]*\.less\b)</string>
                <key>while</key>
                <string>(?=^(?:\s*[})\]`]|\*/|\s*$|\1\s+(\S|$)))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-block-less</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-line-less</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>comment</key>
                <string>Concise style tag scss</string>
                <key>begin</key>
                <string>^(\s*)(?=(?:html-)?style\b[^\s]*\.scss\b)</string>
                <key>while</key>
                <string>(?=^(?:\s*[})\]`]|\*/|\s*$|\1\s+(\S|$)))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-block-scss</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-line-scss</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>comment</key>
                <string>Concise style tag js/ts</string>
                <key>begin</key>
                <string>^(\s*)(?=(?:html-)?style\b[^\s]*\.[tj]s\b)</string>
                <key>while</key>
                <string>(?=^(?:\s*[})\]`]|\*/|\s*$|\1\s+(\S|$)))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-line</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>comment</key>
                <string>Concise style tag</string>
                <key>begin</key>
                <string>^(\s*)(?=(?:html-)?style\b)</string>
                <key>while</key>
                <string>(?=^(?:\s*[})\]`]|\*/|\s*$|\1\s+(\S|$)))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-style-line</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>comment</key>
                <string>Concise script tag</string>
                <key>begin</key>
                <string>^(\s*)(?=(?:html-)?script\b)</string>
                <key>while</key>
                <string>(?=^(?:\s*[})\]`]|\*/|\s*$|\1\s+(\S|$)))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-block</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#concise-script-line</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>comment</key>
                <string>Normal concise tag</string>
                <key>begin</key>
                <string>^([ \t]*)(?=[a-zA-Z0-9_$@.#])</string>
                <key>while</key>
                <string>(?=^(?:\s*[})\]`]|\*/|\s*$|\1\s+(\S|$)))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#concise-open-tag-content</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#content-concise-mode</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>content-embedded-comment</key>
      <dict>
        <key>comment</key>
        <string>Match comment content, but allow Marko placeholders.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.marko</string>
            <key>match</key>
            <string>.</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-script</key>
      <dict>
        <key>comment</key>
        <string>Match script content, but allow Marko placeholders.</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-style</key>
      <dict>
        <key>comment</key>
        <string>Match css content, but allow Marko placeholders.</string>
        <key>name</key>
        <string>meta.embedded.css</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.css</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-style-less</key>
      <dict>
        <key>comment</key>
        <string>Match less content, but allow Marko placeholders.</string>
        <key>name</key>
        <string>meta.embedded.css.less</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.css.less</string>
          </dict>
        </array>
      </dict>
      <key>content-embedded-style-scss</key>
      <dict>
        <key>comment</key>
        <string>Match scss content, but allow Marko placeholders.</string>
        <key>name</key>
        <string>meta.embedded.css.scss</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.css.scss</string>
          </dict>
        </array>
      </dict>
      <key>content-html-mode</key>
      <dict>
        <key>comment</key>
        <string>HTML mode content block.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#scriptlet</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#cdata</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#doctype</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#javascript-comments-after-whitespace</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-html</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>text.marko</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeholder</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.+?</string>
            <key>name</key>
            <string>text.marko</string>
          </dict>
        </array>
      </dict>
      <key>html-args-or-method</key>
      <dict>
        <key>comment</key>
        <string>Matches parenthesis for arguments or continues into method shorthand if a { is found.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tag-type-params</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>Javascript style arguments</string>
            <key>name</key>
            <string>meta.embedded.ts</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>begin</key>
            <string>\s*(?=\()</string>
            <key>end</key>
            <string>(?&lt;=\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts#paren-expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>Attribute method shorthand following parens</string>
            <key>name</key>
            <string>meta.embedded.ts</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>begin</key>
            <string>(?&lt;=\))\s*(?={)</string>
            <key>end</key>
            <string>(?&lt;=})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>html-comment</key>
      <dict>
        <key>comment</key>
        <string>HTML comment</string>
        <key>name</key>
        <string>comment.block.marko</string>
        <key>begin</key>
        <string>\s*(&lt;!(--)?)</string>
        <key>end</key>
        <string>\2&gt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.marko</string>
          </dict>
        </dict>
      </dict>
      <key>cdata</key>
      <dict>
        <key>name</key>
        <string>meta.tag.metadata.cdata.marko</string>
        <key>contentName</key>
        <string>string.other.inline-data.marko</string>
        <key>begin</key>
        <string>\s*&lt;!\[CDATA\[</string>
        <key>end</key>
        <string>]]&gt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>doctype</key>
      <dict>
        <key>name</key>
        <string>meta.tag.metadata.doctype.marko</string>
        <key>begin</key>
        <string>\s*&lt;!(?=(?i:DOCTYPE\s))</string>
        <key>end</key>
        <string>&gt;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\G(?i:DOCTYPE)</string>
            <key>name</key>
            <string>entity.name.tag.marko</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double.marko</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[^\s&gt;]+</string>
            <key>name</key>
            <string>entity.other.attribute-name.marko</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.begin.marko</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.end.marko</string>
          </dict>
        </dict>
      </dict>
      <key>declaration</key>
      <dict>
        <key>name</key>
        <string>meta.tag.metadata.processing.xml.marko</string>
        <key>begin</key>
        <string>(&lt;\?)\s*([a-zA-Z0-9_$-]*)</string>
        <key>end</key>
        <string>(\??&gt;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((?:[^\s=?&gt;]+|\?(?!&gt;))+)(=)(?:("(?:[^"\\]+|\\.)*")|('(?:[^'\\]+|\\.)*')|((?:[^\s?&gt;]+|\?(?!&gt;))+))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name.marko</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value.html</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.marko</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.single.marko</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.marko</string>
              </dict>
            </dict>
          </dict>
        </array>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.tag.marko</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.marko</string>
          </dict>
        </dict>
      </dict>
      <key>invalid</key>
      <dict>
        <key>comment</key>
        <string>Used to highlight characters in places where all valid characters should have been matched.</string>
        <key>match</key>
        <string>\S</string>
        <key>name</key>
        <string>invalid.illegal.character-not-allowed-here.marko</string>
      </dict>
      <key>javascript-comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>JavaScript /* block comment */</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>begin</key>
            <string>\s*(?=/\*)</string>
            <key>end</key>
            <string>(?&lt;=\*/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>JavaScript // single line comment</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>match</key>
            <string>\s*//.*$</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>javascript-comments-after-whitespace</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>JavaScript /* block comment */</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>begin</key>
            <string>(?:^|\s+)(?=/\*)</string>
            <key>end</key>
            <string>(?&lt;=\*/)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>JavaScript // single line comment</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>match</key>
            <string>(?:^|\s+)//.*$</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>javascript-expression</key>
      <dict>
        <key>comment</key>
        <string>Matches JavaScript source code, but always continues for certain types of expressions.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-comments</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>We must match the some expressions ourselves since otherwise the js grammar can overstep.</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>match</key>
            <string>(?:\s*\b(?:as|await|extends|in|instanceof|satisfies|keyof|new|typeof|void))+\s+(?![:=/,;&gt;])[a-zA-Z0-9_$@#]*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>We must match regexps since otherwise it can be cutoff by self closed tags or comments.</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>match</key>
            <string>(?&lt;![a-zA-Z0-9%).&lt;\]}])\s*/(?:[^\\\[/]+|\\.|\[(?:[^\\\]]+|\\.)*\])*/[a-zA-Z]*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.regexp.ts</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#regexp</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>source.ts</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
      </dict>
      <key>open-tag-content</key>
      <dict>
        <key>comment</key>
        <string>Matches everything within an open tag from tag name to the last attr.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#invalid-close-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-before-attrs</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>Attributes begin after the first space within the tag name</string>
            <key>begin</key>
            <string>(?!/?&gt;)</string>
            <key>end</key>
            <string>(?=/?&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#attrs</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>placeholder</key>
      <dict>
        <key>comment</key>
        <string>A Marko template literal expression (allows $!{}).</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>\$!?{</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.ts</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.ts</string>
          </dict>
        </dict>
      </dict>
      <key>javascript-placeholder</key>
      <dict>
        <key>comment</key>
        <string>A JavaScript style template literal expression.</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>\${</string>
        <key>end</key>
        <string>}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.begin.ts</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.template-expression.end.ts</string>
          </dict>
        </dict>
      </dict>
      <key>scriptlet</key>
      <dict>
        <key>comment</key>
        <string>An inline JavaScript scriptlet.</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>^\s*(\$)\s+</string>
        <key>end</key>
        <string>$</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts</string>
          </dict>
        </array>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.scriptlet.marko</string>
          </dict>
        </dict>
      </dict>
      <key>tag-before-attrs</key>
      <dict>
        <key>comment</key>
        <string>Everything in a tag before the attributes content</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#tag-name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#tag-shorthand-class-or-id</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>Variable for a tag</string>
            <key>name</key>
            <string>meta.embedded.ts</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>begin</key>
            <string>/(?![/*])</string>
            <key>end</key>
            <string>(?=[,;(|/&gt;&lt;]|:?=|\s+[^:]|$)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.tag-variable.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>comment</key>
                <string>Match identifiers</string>
                <key>match</key>
                <string>[a-zA-Z$_][0-9a-zA-Z$_]*</string>
                <key>name</key>
                <string>variable.other.constant.object.ts</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Match object pattern</string>
                <key>begin</key>
                <string>{</string>
                <key>end</key>
                <string>}</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#object-binding-element</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#javascript-expression</string>
                  </dict>
                </array>
                <key>captures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.binding-pattern.object.ts</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>comment</key>
                <string>Match array pattern</string>
                <key>begin</key>
                <string>\[</string>
                <key>end</key>
                <string>]</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#array-binding-element</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#javascript-expression</string>
                  </dict>
                </array>
                <key>captures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.binding-pattern.array.ts</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>comment</key>
                <string>Match type</string>
                <key>begin</key>
                <string>\s*(:)(?!=)</string>
                <key>end</key>
                <string>(?=[,;\](]|/&gt;|(?&lt;=[^=&gt;])&gt;|(?&lt;!^|[!~*%&amp;^|?:]|[!~*%&amp;^|?/&lt;&gt;+=-]=|[=&gt;]&gt;|[^.]\.|[^-]-|[^+]\+|[a-zA-Z0-9%).&lt;\]}]\s/|[^.$\w]await|[^.$\w]async|[^.$\w]class|[^.$\w]function|[^.$\w]keyof|[^.$\w]new|[^.$\w]readonly|[^.$\w]infer|[^.$\w]typeof|[^.$\w]void)\s+(?![\n{+!~*%&amp;^|?:]|[&lt;&gt;/=-]=|[=&gt;]&gt;|\.[^.]|-[^-]|/[^&gt;]|(?:in|instanceof|satisfies|as|extends)\s+[^:=/,;&gt;]))</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#type</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#javascript-expression</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.type.annotation.ts</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>#javascript-expression</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>Parameters for a tag</string>
            <key>contentName</key>
            <string>source.ts</string>
            <key>begin</key>
            <string>\s*\|</string>
            <key>end</key>
            <string>\|</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.scope.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.scope.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ts#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#string</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#decorator</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#destructuring-parameter</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#parameter-name</string>
              </dict>
              <dict>
                <key>name</key>
                <string>meta.type.annotation.ts</string>
                <key>begin</key>
                <string>(:)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.type.annotation.ts</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=[,|])|(?==[^&gt;])</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ts#type</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts#variable-initializer</string>
              </dict>
              <dict>
                <key>name</key>
                <string>punctuation.separator.parameter.ts</string>
                <key>match</key>
                <string>,</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.ts</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#html-args-or-method</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attr-value</string>
          </dict>
        </array>
      </dict>
      <key>tag-html</key>
      <dict>
        <key>comment</key>
        <string>Matches an HTML tag and its contents</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>HTML void elements</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr|const|debug|id|let|lifecycle|log|return)\b)</string>
            <key>end</key>
            <string>/?&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>Marko html-comment tag</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=html-comment\b)</string>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;|&lt;/html-comment&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Comment tag body content</string>
                <key>begin</key>
                <string>&gt;</string>
                <key>end</key>
                <string>\s*(?:&lt;/&gt;|&lt;/html-comment&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-comment</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>HTML style tag with less</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=((?:html-)?style)\b[^\s]*\.less\b)</string>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;|&lt;/\2&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Style body content</string>
                <key>contentName</key>
                <string>source.less</string>
                <key>begin</key>
                <string>&gt;</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?style)?(&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-style-less</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>HTML style tag with scss</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=((?:html-)?style)\b[^\s]*\.scss\b)</string>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;|&lt;/\2&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Style body content</string>
                <key>contentName</key>
                <string>source.scss</string>
                <key>begin</key>
                <string>&gt;</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?style)?(&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-style-scss</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>HTML style tag with js/ts</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=((?:html-)?style)\b[^\s]*\.[tj]s\b)</string>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;|&lt;/\2&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Style body content</string>
                <key>contentName</key>
                <string>source.ts</string>
                <key>begin</key>
                <string>&gt;</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?style)?(&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-script</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>HTML style tag</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=((?:html-)?style)\b)</string>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;|&lt;/\2&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Style body content</string>
                <key>contentName</key>
                <string>source.css</string>
                <key>begin</key>
                <string>&gt;</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?style)?(&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-style</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>HTML script tag</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=((?:html-)?script)\b)</string>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;|&lt;/\2&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Script body content</string>
                <key>contentName</key>
                <string>source.ts</string>
                <key>begin</key>
                <string>&gt;</string>
                <key>end</key>
                <string>\s*(&lt;/)((?:html-)?script)?(&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-embedded-script</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>HTML normal tag</string>
            <key>begin</key>
            <string>\s*(&lt;)(?=[.#$]|([a-zA-Z0-9_$@-]+))</string>
            <key>end</key>
            <string>/&gt;|(?&lt;=&lt;/&gt;|&lt;/\2&gt;)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#open-tag-content</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>Body content</string>
                <key>begin</key>
                <string>&gt;</string>
                <key>end</key>
                <string>\s*(&lt;/)([a-zA-Z0-9_$:@.#-]+)?(.*?)(&gt;)</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#content-html-mode</string>
                  </dict>
                </array>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.marko</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#tag-name</string>
                      </dict>
                      <dict>
                        <key>include</key>
                        <string>#tag-shorthand-class-or-id</string>
                      </dict>
                    </array>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>patterns</key>
                    <array>
                      <dict>
                        <key>include</key>
                        <string>#invalid</string>
                      </dict>
                    </array>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.marko</string>
                  </dict>
                </dict>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.marko</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.marko</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>tag-type-args</key>
      <dict>
        <key>comment</key>
        <string>Type args after the tag name</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>(?=&lt;)</string>
        <key>end</key>
        <string>(?&lt;=&gt;)</string>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;=&gt;)(?=[ 	]*&lt;)</string>
            <key>end</key>
            <string>(?=.)</string>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-type-params</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>source.ts#type-arguments</string>
          </dict>
        </array>
      </dict>
      <key>tag-type-params</key>
      <dict>
        <key>comment</key>
        <string>Type params before tag params or a default shorthand method</string>
        <key>name</key>
        <string>meta.embedded.ts</string>
        <key>contentName</key>
        <string>source.ts</string>
        <key>begin</key>
        <string>(?!^)[ 	]*(?=&lt;)</string>
        <key>end</key>
        <string>(?&lt;=&gt;)</string>
        <key>applyEndPatternLast</key>
        <integer>1</integer>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.ts#type-parameters</string>
          </dict>
        </array>
      </dict>
      <key>tag-shorthand-class-or-id</key>
      <dict>
        <key>comment</key>
        <string>Shorthand class or ID attribute</string>
        <key>begin</key>
        <string>(?=[#.])</string>
        <key>end</key>
        <string>$|(?=--|[^a-zA-Z0-9_$#.-])</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#javascript-placeholder</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:[#.a-zA-Z0-9_-]+|\$(?!{))+</string>
            <key>name</key>
            <string>entity.other.attribute-name.marko</string>
          </dict>
        </array>
      </dict>
      <key>tag-name</key>
      <dict>
        <key>comment</key>
        <string>Matches the tag name.</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\G(style)\b(\.[a-zA-Z0-9$_-]+(?:\.[a-zA-Z0-9$_-]+)*)|([a-zA-Z0-9_@](?:[a-zA-Z0-9_@-]+|:(?!=))*)</string>
            <key>end</key>
            <string>(?=.)</string>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#tag-type-args</string>
              </dict>
            </array>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.type.builtin.marko</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.marko.css</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>support.type.builtin.marko</string>
                    <key>match</key>
                    <string>(script|style|html-script|html-style|html-comment)(?=\b)(?![-:@])</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>keyword.control.flow.marko</string>
                    <key>match</key>
                    <string>(for|if|while|else-if|else|try|await|return)(?=\b)(?![-:@])</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>support.function.marko</string>
                    <key>match</key>
                    <string>(const|context|debug|define|id|let|log|lifecycle)(?=\b)(?![-:@])</string>
                  </dict>
                  <dict>
                    <key>comment</key>
                    <string>Attribute tag.</string>
                    <key>name</key>
                    <string>entity.other.attribute-name.marko</string>
                    <key>match</key>
                    <string>@.+</string>
                  </dict>
                  <dict>
                    <key>comment</key>
                    <string>Native or userland tag.</string>
                    <key>name</key>
                    <string>entity.name.tag.marko</string>
                    <key>match</key>
                    <string>.+</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(?=[a-zA-Z0-9$_]|-[^-])</string>
            <key>end</key>
            <string>(?=[^a-zA-Z0-9$_-]|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#javascript-placeholder</string>
              </dict>
              <dict>
                <key>match</key>
                <string>(?:[a-zA-Z0-9_-]+|\$(?!{))+</string>
                <key>name</key>
                <string>entity.name.tag.marko</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>invalid-close-tag</key>
      <dict>
        <key>name</key>
        <string>invalid.illegal.character-not-allowed-here.marko</string>
        <key>begin</key>
        <string>\s*&lt;/.*?</string>
        <key>end</key>
        <string>&gt;</string>
      </dict>
    </dict>
  </dict>
</plist>
